version: "3.8"
services:
  game:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    command: /bin/sh -c "npm run dev & ngrok http 8080 --log stdout"
