version: "3.8"
services:
  game:
    build: ./client
    ports:
      - "8080:8080"
    volumes:
      - ./client:/app
      - ./shared_core:/shared_core 
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev
    restart: always
  server:
    build: ./server
    ports:
      - "3000:3000"

    # this is how it was in the beginning
    # volumes:
    #   - ./server:/server
    #   - /server/node_modules
    # working_dir: /server

    # add this to hot reload server
    # volumes:
    #   - ./server:/server        # keep for live editing
    #   - /server/node_modules    # named/anon vol to avoid host pollution
    # working_dir: /server
    # command: npm run dev        # ts-node-dev

    command: node dist/index.js
