version: "3.8"
services:
  game:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true  # 🔹 Faz com que Webpack monitore mudanças corretamente
    command: npm run dev
    restart: always
